// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: boards.sql

package query

import (
	"context"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (category_id, slug, name, description, position)
VALUES (?, ?, ?, ?, ?)
RETURNING id, category_id, slug, name, description, position, created_at, updated_at
`

type CreateBoardParams struct {
	CategoryID  *int64 `json:"category_id"`
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Position    int64  `json:"position"`
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, createBoard,
		arg.CategoryID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Position,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBoardByID = `-- name: GetBoardByID :one
SELECT id, category_id, slug, name, description, position, created_at, updated_at FROM boards WHERE id = ? LIMIT 1
`

func (q *Queries) GetBoardByID(ctx context.Context, id int64) (Board, error) {
	row := q.db.QueryRowContext(ctx, getBoardByID, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBoardBySlug = `-- name: GetBoardBySlug :one
SELECT id, category_id, slug, name, description, position, created_at, updated_at FROM boards WHERE slug = ? LIMIT 1
`

func (q *Queries) GetBoardBySlug(ctx context.Context, slug string) (Board, error) {
	row := q.db.QueryRowContext(ctx, getBoardBySlug, slug)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBoards = `-- name: ListBoards :many
SELECT id, category_id, slug, name, description, position, created_at, updated_at FROM boards ORDER BY position, id
`

func (q *Queries) ListBoards(ctx context.Context) ([]Board, error) {
	rows, err := q.db.QueryContext(ctx, listBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Board{}
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardsByCategoryID = `-- name: ListBoardsByCategoryID :many
SELECT id, category_id, slug, name, description, position, created_at, updated_at FROM boards WHERE category_id = ? ORDER BY position, id
`

func (q *Queries) ListBoardsByCategoryID(ctx context.Context, categoryID *int64) ([]Board, error) {
	rows, err := q.db.QueryContext(ctx, listBoardsByCategoryID, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Board{}
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
