// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: community_members.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createCommunityMember = `-- name: CreateCommunityMember :one
INSERT INTO community_members (community_id, user_id)
VALUES ($1, $2)
RETURNING id, community_id, user_id, created_at, updated_at
`

type CreateCommunityMemberParams struct {
	CommunityID uuid.UUID `json:"community_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateCommunityMember(ctx context.Context, arg CreateCommunityMemberParams) (CommunityMember, error) {
	row := q.db.QueryRow(ctx, createCommunityMember, arg.CommunityID, arg.UserID)
	var i CommunityMember
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
