// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: community_roles.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createCommunityRole = `-- name: CreateCommunityRole :one
INSERT INTO community_roles (community_id, name)
VALUES ($1, $2)
RETURNING id, community_id, name, created_at, updated_at
`

type CreateCommunityRoleParams struct {
	CommunityID uuid.UUID `json:"community_id"`
	Name        string    `json:"name"`
}

func (q *Queries) CreateCommunityRole(ctx context.Context, arg CreateCommunityRoleParams) (CommunityRole, error) {
	row := q.db.QueryRow(ctx, createCommunityRole, arg.CommunityID, arg.Name)
	var i CommunityRole
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
