// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: community_member_roles.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createCommunityMemberRole = `-- name: CreateCommunityMemberRole :one
INSERT INTO community_member_roles (community_id, community_member_id, community_role_id)
VALUES ($1, $2, $3)
RETURNING id, community_id, community_member_id, community_role_id, created_at, updated_at
`

type CreateCommunityMemberRoleParams struct {
	CommunityID       uuid.UUID `json:"community_id"`
	CommunityMemberID uuid.UUID `json:"community_member_id"`
	CommunityRoleID   uuid.UUID `json:"community_role_id"`
}

func (q *Queries) CreateCommunityMemberRole(ctx context.Context, arg CreateCommunityMemberRoleParams) (CommunityMemberRole, error) {
	row := q.db.QueryRow(ctx, createCommunityMemberRole, arg.CommunityID, arg.CommunityMemberID, arg.CommunityRoleID)
	var i CommunityMemberRole
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.CommunityMemberID,
		&i.CommunityRoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
