// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: communities.sql

package query

import (
	"context"
)

const createCommunity = `-- name: CreateCommunity :one
INSERT INTO communities (name, identifier)
VALUES ($1, $2)
RETURNING id, name, identifier, created_at, updated_at
`

type CreateCommunityParams struct {
	Name       string `json:"name"`
	Identifier string `json:"identifier"`
}

func (q *Queries) CreateCommunity(ctx context.Context, arg CreateCommunityParams) (Community, error) {
	row := q.db.QueryRow(ctx, createCommunity, arg.Name, arg.Identifier)
	var i Community
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Identifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommunityByIdentifier = `-- name: GetCommunityByIdentifier :one
SELECT id, name, identifier, created_at, updated_at FROM communities WHERE identifier = $1 LIMIT 1
`

func (q *Queries) GetCommunityByIdentifier(ctx context.Context, identifier string) (Community, error) {
	row := q.db.QueryRow(ctx, getCommunityByIdentifier, identifier)
	var i Community
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Identifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
