// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_references.sql

package query

import (
	"context"
	"strings"
)

const createPostReference = `-- name: CreatePostReference :one
INSERT INTO post_references (post_id, referenced_post_id)
VALUES (?, ?)
RETURNING id, post_id, referenced_post_id, created_at, updated_at
`

type CreatePostReferenceParams struct {
	PostID           int64 `json:"post_id"`
	ReferencedPostID int64 `json:"referenced_post_id"`
}

func (q *Queries) CreatePostReference(ctx context.Context, arg CreatePostReferenceParams) (PostReference, error) {
	row := q.db.QueryRowContext(ctx, createPostReference, arg.PostID, arg.ReferencedPostID)
	var i PostReference
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ReferencedPostID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPostReferencesByReferencedPostIDs = `-- name: ListPostReferencesByReferencedPostIDs :many
SELECT id, post_id, referenced_post_id, created_at, updated_at FROM post_references
WHERE referenced_post_id IN (/*SLICE:referenced_post_ids*/?)
ORDER BY referenced_post_id, post_id
`

func (q *Queries) ListPostReferencesByReferencedPostIDs(ctx context.Context, referencedPostIds []int64) ([]PostReference, error) {
	query := listPostReferencesByReferencedPostIDs
	var queryParams []interface{}
	if len(referencedPostIds) > 0 {
		for _, v := range referencedPostIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:referenced_post_ids*/?", strings.Repeat(",?", len(referencedPostIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:referenced_post_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostReference{}
	for rows.Next() {
		var i PostReference
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ReferencedPostID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
