// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: threads.sql

package query

import (
	"context"

	"github.com/groobb/groobb/go/internal/sqlitetime"
)

const createThread = `-- name: CreateThread :one
INSERT INTO threads (board_id, user_id, title)
VALUES (?, ?, ?)
RETURNING id, board_id, user_id, title, posts_count, last_post_id, last_posted_at, created_at, updated_at
`

type CreateThreadParams struct {
	BoardID int64  `json:"board_id"`
	UserID  *int64 `json:"user_id"`
	Title   string `json:"title"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.db.QueryRowContext(ctx, createThread, arg.BoardID, arg.UserID, arg.Title)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.UserID,
		&i.Title,
		&i.PostsCount,
		&i.LastPostID,
		&i.LastPostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getThreadByID = `-- name: GetThreadByID :one
SELECT id, board_id, user_id, title, posts_count, last_post_id, last_posted_at, created_at, updated_at FROM threads WHERE id = ? LIMIT 1
`

func (q *Queries) GetThreadByID(ctx context.Context, id int64) (Thread, error) {
	row := q.db.QueryRowContext(ctx, getThreadByID, id)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.UserID,
		&i.Title,
		&i.PostsCount,
		&i.LastPostID,
		&i.LastPostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecentThreadsPerBoard = `-- name: ListRecentThreadsPerBoard :many
SELECT threads.id, threads.board_id, threads.user_id, threads.title, threads.posts_count, threads.last_post_id, threads.last_posted_at, threads.created_at, threads.updated_at FROM boards
JOIN threads ON threads.id IN (
    SELECT recent.id FROM threads AS recent
    WHERE recent.board_id = boards.id
    ORDER BY recent.last_posted_at DESC, recent.id DESC
    LIMIT ?1
)
ORDER BY boards.position, boards.id, threads.last_posted_at DESC, threads.id DESC
`

func (q *Queries) ListRecentThreadsPerBoard(ctx context.Context, perBoard int64) ([]Thread, error) {
	rows, err := q.db.QueryContext(ctx, listRecentThreadsPerBoard, perBoard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Thread{}
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.UserID,
			&i.Title,
			&i.PostsCount,
			&i.LastPostID,
			&i.LastPostedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsByBoardID = `-- name: ListThreadsByBoardID :many
SELECT id, board_id, user_id, title, posts_count, last_post_id, last_posted_at, created_at, updated_at FROM threads
WHERE board_id = ?
ORDER BY last_posted_at DESC, id DESC
`

func (q *Queries) ListThreadsByBoardID(ctx context.Context, boardID int64) ([]Thread, error) {
	rows, err := q.db.QueryContext(ctx, listThreadsByBoardID, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Thread{}
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.UserID,
			&i.Title,
			&i.PostsCount,
			&i.LastPostID,
			&i.LastPostedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateThreadLastPost = `-- name: UpdateThreadLastPost :exec
UPDATE threads
SET posts_count = ?,
    last_post_id = ?,
    last_posted_at = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateThreadLastPostParams struct {
	PostsCount   int64           `json:"posts_count"`
	LastPostID   *int64          `json:"last_post_id"`
	LastPostedAt sqlitetime.Time `json:"last_posted_at"`
	ID           int64           `json:"id"`
}

func (q *Queries) UpdateThreadLastPost(ctx context.Context, arg UpdateThreadLastPostParams) error {
	_, err := q.db.ExecContext(ctx, updateThreadLastPost,
		arg.PostsCount,
		arg.LastPostID,
		arg.LastPostedAt,
		arg.ID,
	)
	return err
}
