// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_passwords.sql

package query

import (
	"context"
)

const createUserPassword = `-- name: CreateUserPassword :one
INSERT INTO user_passwords (user_id, password_digest)
VALUES (?, ?)
RETURNING id, user_id, password_digest, created_at, updated_at
`

type CreateUserPasswordParams struct {
	UserID         int64  `json:"user_id"`
	PasswordDigest string `json:"password_digest"`
}

func (q *Queries) CreateUserPassword(ctx context.Context, arg CreateUserPasswordParams) (UserPassword, error) {
	row := q.db.QueryRowContext(ctx, createUserPassword, arg.UserID, arg.PasswordDigest)
	var i UserPassword
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPasswordByUserID = `-- name: GetUserPasswordByUserID :one
SELECT id, user_id, password_digest, created_at, updated_at FROM user_passwords WHERE user_id = ? LIMIT 1
`

func (q *Queries) GetUserPasswordByUserID(ctx context.Context, userID int64) (UserPassword, error) {
	row := q.db.QueryRowContext(ctx, getUserPasswordByUserID, userID)
	var i UserPassword
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPasswordDigestByUserID = `-- name: UpdateUserPasswordDigestByUserID :exec
UPDATE user_passwords
SET password_digest = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE user_id = ?
`

type UpdateUserPasswordDigestByUserIDParams struct {
	PasswordDigest string `json:"password_digest"`
	UserID         int64  `json:"user_id"`
}

func (q *Queries) UpdateUserPasswordDigestByUserID(ctx context.Context, arg UpdateUserPasswordDigestByUserIDParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPasswordDigestByUserID, arg.PasswordDigest, arg.UserID)
	return err
}
