// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_two_factor_auths.sql

package query

import (
	"context"
)

const createUserTwoFactorAuth = `-- name: CreateUserTwoFactorAuth :one
INSERT INTO user_two_factor_auths (user_id, secret)
VALUES (?, ?)
ON CONFLICT (user_id) DO NOTHING
RETURNING id, user_id, secret, enabled, enabled_at, recovery_codes, created_at, updated_at
`

type CreateUserTwoFactorAuthParams struct {
	UserID int64  `json:"user_id"`
	Secret string `json:"secret"`
}

func (q *Queries) CreateUserTwoFactorAuth(ctx context.Context, arg CreateUserTwoFactorAuthParams) (UserTwoFactorAuth, error) {
	row := q.db.QueryRowContext(ctx, createUserTwoFactorAuth, arg.UserID, arg.Secret)
	var i UserTwoFactorAuth
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Secret,
		&i.Enabled,
		&i.EnabledAt,
		&i.RecoveryCodes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserTwoFactorAuthByUserID = `-- name: DeleteUserTwoFactorAuthByUserID :exec
DELETE FROM user_two_factor_auths WHERE user_id = ?
`

func (q *Queries) DeleteUserTwoFactorAuthByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserTwoFactorAuthByUserID, userID)
	return err
}

const enableUserTwoFactorAuth = `-- name: EnableUserTwoFactorAuth :execrows
UPDATE user_two_factor_auths
SET enabled = TRUE,
    enabled_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    recovery_codes = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE user_id = ? AND enabled = FALSE
`

type EnableUserTwoFactorAuthParams struct {
	RecoveryCodes string `json:"recovery_codes"`
	UserID        int64  `json:"user_id"`
}

func (q *Queries) EnableUserTwoFactorAuth(ctx context.Context, arg EnableUserTwoFactorAuthParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, enableUserTwoFactorAuth, arg.RecoveryCodes, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEnabledUserTwoFactorAuthByUserID = `-- name: GetEnabledUserTwoFactorAuthByUserID :one
SELECT id, user_id, secret, enabled, enabled_at, recovery_codes, created_at, updated_at FROM user_two_factor_auths WHERE user_id = ? AND enabled = TRUE LIMIT 1
`

func (q *Queries) GetEnabledUserTwoFactorAuthByUserID(ctx context.Context, userID int64) (UserTwoFactorAuth, error) {
	row := q.db.QueryRowContext(ctx, getEnabledUserTwoFactorAuthByUserID, userID)
	var i UserTwoFactorAuth
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Secret,
		&i.Enabled,
		&i.EnabledAt,
		&i.RecoveryCodes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTwoFactorAuthByUserID = `-- name: GetUserTwoFactorAuthByUserID :one
SELECT id, user_id, secret, enabled, enabled_at, recovery_codes, created_at, updated_at FROM user_two_factor_auths WHERE user_id = ? LIMIT 1
`

func (q *Queries) GetUserTwoFactorAuthByUserID(ctx context.Context, userID int64) (UserTwoFactorAuth, error) {
	row := q.db.QueryRowContext(ctx, getUserTwoFactorAuthByUserID, userID)
	var i UserTwoFactorAuth
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Secret,
		&i.Enabled,
		&i.EnabledAt,
		&i.RecoveryCodes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserTwoFactorAuthRecoveryCodes = `-- name: UpdateUserTwoFactorAuthRecoveryCodes :exec
UPDATE user_two_factor_auths
SET recovery_codes = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE user_id = ?
`

type UpdateUserTwoFactorAuthRecoveryCodesParams struct {
	RecoveryCodes string `json:"recovery_codes"`
	UserID        int64  `json:"user_id"`
}

func (q *Queries) UpdateUserTwoFactorAuthRecoveryCodes(ctx context.Context, arg UpdateUserTwoFactorAuthRecoveryCodesParams) error {
	_, err := q.db.ExecContext(ctx, updateUserTwoFactorAuthRecoveryCodes, arg.RecoveryCodes, arg.UserID)
	return err
}
