// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_two_factor_auths.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createUserTwoFactorAuth = `-- name: CreateUserTwoFactorAuth :one
INSERT INTO user_two_factor_auths (user_id, secret)
VALUES ($1, $2)
ON CONFLICT (user_id) DO NOTHING
RETURNING id, user_id, secret, enabled, enabled_at, recovery_codes, created_at, updated_at
`

type CreateUserTwoFactorAuthParams struct {
	UserID uuid.UUID `json:"user_id"`
	Secret string    `json:"secret"`
}

func (q *Queries) CreateUserTwoFactorAuth(ctx context.Context, arg CreateUserTwoFactorAuthParams) (UserTwoFactorAuth, error) {
	row := q.db.QueryRow(ctx, createUserTwoFactorAuth, arg.UserID, arg.Secret)
	var i UserTwoFactorAuth
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Secret,
		&i.Enabled,
		&i.EnabledAt,
		&i.RecoveryCodes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserTwoFactorAuthByUserID = `-- name: DeleteUserTwoFactorAuthByUserID :exec
DELETE FROM user_two_factor_auths WHERE user_id = $1
`

func (q *Queries) DeleteUserTwoFactorAuthByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserTwoFactorAuthByUserID, userID)
	return err
}

const enableUserTwoFactorAuth = `-- name: EnableUserTwoFactorAuth :execrows
UPDATE user_two_factor_auths
SET enabled = true, enabled_at = NOW(), recovery_codes = $2, updated_at = NOW()
WHERE user_id = $1 AND enabled = false
`

type EnableUserTwoFactorAuthParams struct {
	UserID        uuid.UUID `json:"user_id"`
	RecoveryCodes []string  `json:"recovery_codes"`
}

func (q *Queries) EnableUserTwoFactorAuth(ctx context.Context, arg EnableUserTwoFactorAuthParams) (int64, error) {
	result, err := q.db.Exec(ctx, enableUserTwoFactorAuth, arg.UserID, arg.RecoveryCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEnabledUserTwoFactorAuthByUserID = `-- name: GetEnabledUserTwoFactorAuthByUserID :one
SELECT id, user_id, secret, enabled, enabled_at, recovery_codes, created_at, updated_at FROM user_two_factor_auths WHERE user_id = $1 AND enabled = true LIMIT 1
`

func (q *Queries) GetEnabledUserTwoFactorAuthByUserID(ctx context.Context, userID uuid.UUID) (UserTwoFactorAuth, error) {
	row := q.db.QueryRow(ctx, getEnabledUserTwoFactorAuthByUserID, userID)
	var i UserTwoFactorAuth
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Secret,
		&i.Enabled,
		&i.EnabledAt,
		&i.RecoveryCodes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTwoFactorAuthByUserID = `-- name: GetUserTwoFactorAuthByUserID :one
SELECT id, user_id, secret, enabled, enabled_at, recovery_codes, created_at, updated_at FROM user_two_factor_auths WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserTwoFactorAuthByUserID(ctx context.Context, userID uuid.UUID) (UserTwoFactorAuth, error) {
	row := q.db.QueryRow(ctx, getUserTwoFactorAuthByUserID, userID)
	var i UserTwoFactorAuth
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Secret,
		&i.Enabled,
		&i.EnabledAt,
		&i.RecoveryCodes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserTwoFactorAuthRecoveryCodes = `-- name: UpdateUserTwoFactorAuthRecoveryCodes :exec
UPDATE user_two_factor_auths
SET recovery_codes = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateUserTwoFactorAuthRecoveryCodesParams struct {
	UserID        uuid.UUID `json:"user_id"`
	RecoveryCodes []string  `json:"recovery_codes"`
}

func (q *Queries) UpdateUserTwoFactorAuthRecoveryCodes(ctx context.Context, arg UpdateUserTwoFactorAuthRecoveryCodesParams) error {
	_, err := q.db.Exec(ctx, updateUserTwoFactorAuthRecoveryCodes, arg.UserID, arg.RecoveryCodes)
	return err
}
