// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_sessions.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_sessions (user_id, token, ip_address, user_agent)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token, ip_address, user_agent, signed_in_at, created_at, updated_at
`

type CreateUserSessionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	IpAddress string    `json:"ip_address"`
	UserAgent string    `json:"user_agent"`
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.UserID,
		arg.Token,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.IpAddress,
		&i.UserAgent,
		&i.SignedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserSessionByToken = `-- name: DeleteUserSessionByToken :exec
DELETE FROM user_sessions WHERE token = $1
`

func (q *Queries) DeleteUserSessionByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteUserSessionByToken, token)
	return err
}

const getUserSessionByToken = `-- name: GetUserSessionByToken :one
SELECT id, user_id, token, ip_address, user_agent, signed_in_at, created_at, updated_at FROM user_sessions WHERE token = $1 LIMIT 1
`

func (q *Queries) GetUserSessionByToken(ctx context.Context, token string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionByToken, token)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.IpAddress,
		&i.UserAgent,
		&i.SignedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
