services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    depends_on:
      - caddy
    volumes:
      - .:/workspace
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/go/.cache/go-build
    ports:
      - "4300:8080" # Go
    stdin_open: true
    tty: true
    working_dir: /workspace
    environment:
      - OP_SERVICE_ACCOUNT_TOKEN=${OP_SERVICE_ACCOUNT_TOKEN:-}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}

  caddy:
    image: caddy:2-alpine
    ports:
      - "4301:8080"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro

volumes:
  go-build-cache:
  go-mod-cache:
