// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package email_confirmation

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"fmt"

	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

// EnText renders the English plain-text body. Like JaText it is built with
// templ.Raw from a formatted string so the line breaks survive verbatim.
//
// [Ja] EnText は英語のプレーンテキスト本文を描画します。JaText と同様、整形済み
// 文字列から templ.Raw で組み立て、改行をそのまま保ちます。
func EnText(data Data) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw(fmt.Sprintf(
			"Here is the confirmation code for %s.\n\n"+
				"Enter the code below to confirm your email address.\n\n"+
				"%s\n\n"+
				"This code is valid for 15 minutes.\n\n"+
				"If you did not request this email, please disregard it.\n\n"+
				"Groobb\n",
			data.Email, data.Code,
		)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
