// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package email_confirmation

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"fmt"

	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

// JaText renders the Japanese plain-text body. It is built with templ.Raw from a
// formatted string so the line breaks survive verbatim: templ's default
// expression output is for HTML (it escapes and collapses whitespace), which
// would mangle a plain-text email.
//
// [Ja] JaText は日本語のプレーンテキスト本文を描画します。整形済み文字列から
// templ.Raw で組み立て、改行をそのまま保ちます。templ の既定の式出力は HTML 向け
// (エスケープと空白の畳み込みを行う) で、プレーンテキストメールでは崩れてしまうためです。
func JaText(data Data) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw(fmt.Sprintf(
			"%s 宛に確認用コードをお送りします。\n\n"+
				"下記のコードを入力して、メールアドレスの確認を完了してください。\n\n"+
				"%s\n\n"+
				"このコードの有効期間は 15 分です。\n\n"+
				"このメールに心当たりが無い場合は、破棄してください。\n\n"+
				"Groobb\n",
			data.Email, data.Code,
		)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
